### ISSUE TITLE
Anomaly annotation shows on wrong date range on feature breakdown chart

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/anomaly-detection-kibana-plugin#280] opened 2020-08-13 18:13 UTC
We show anomaly result as line plot on AD history chart and show annotation on feature breakdown chart. When zoom in some period, feature breakdown may show annotation on normal detection intervals.

![Screen Shot 2020-08-13 at 11 09 48 AM](https://user-images.githubusercontent.com/49084640/90171191-fb855780-dd55-11ea-92fe-03f6aba6a212.png)

**Comment by ohltyler** [comment] 2021-02-02 18:02
@ylwu-amzn I'm not able to reproduce this, in the real-time or historical case anymore.

**Comment by ylwu-amzn** [comment] 2021-02-02 18:57
Not sure if we have fixed this in historical detector changes, let's do more test and close this if not able to reproduce it.

**Comment by ohltyler** [comment] 2021-02-02 19:11
Have been testing different edge cases, still cannot reproduce. Would have been caused by an issue in calculating the anomaly's `endTime` which determines the x coordinates of the annotation. Closing.

**Closed by ohltyler** 2021-02-02 19:11 UTC
Labels: bug
